name: CI/CD Pipeline
# cuando se suve a dev se ahcen las pruebas y luego se copia a main
on:
  push:
    branches:
      - dev
  workflow_dispatch: #para poder ejecutarlo manualmente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener este archivo con tus dependencias

      - name: Run tests
        run: |
          pytest src/test_app.py
  
  merge_to_main:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action deploy"
          git config --global user.email "action@github.com"

      - name: Merge `dev` into `main`
        run: |
          git checkout main
          git merge dev
          git push origin main